env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2020
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  "semi":
    - "off"
  "@typescript-eslint/semi":
    - error
  "semi-style":
    - "error"
    - "last"
  "no-extra-semi": 
    - "error"
  "no-unexpected-multiline": 
    - "error"
  "no-unreachable":
    - "error"
  "react/prop-types": 
    - "off"
  "no-undef":
    - "off"
  "multiline-ternary":
    - "off"
