version: '3.8'
services:
  app:
    container_name: app
    tty: true
    build:
      # args:
      #   user: sammy
      #   uid: 1000
      context: ./backend/app
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./backend/src:/var/www
  nginx:
    container_name: nginx
    tty: true
    image: nginx
    ports:
      - 9000:80
    volumes:
      - ./backend/src:/var/www
      - ./backend/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  db:
    container_name: 'mysql_db'
    image: 'arm64v8/mysql:oracle'
    command: --default-authentication-plugin=mysql_native_password
    tty: true
    ports:
      - 3306
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
    volumes:
      - 'mysql_driver:/var/lib/mysql'
    # healthcheck:
    #   test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
    #   retries: 3
    #   timeout: 5s

volumes:
  mysql_driver:
    driver: local
