version: '3.8'
services:
  nginx:
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./backend/src:/var/www
      - ./backend/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /docker-volumes/etc/letsencrypt/live/api.michilog.space/fullchain.pem:/etc/nginx/conf.d/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/api.michilog.space/privkey.pem:/etc/nginx/conf.d/privkey.pem
  db:
    image: 'mysql:8.0.31'
